Adding TensorRT options to 'configure' and updating template names

diff --git a/TensorFlow/OpenShift/configure b/TensorFlow/OpenShift/configure
--- a/TensorFlow/OpenShift/configure
+++ b/TensorFlow/OpenShift/configure
@@ -29,6 +29,7 @@ while test $# -gt 0; do
             echo "  --use-gpu         |  Use the GPU"
 	    echo "  --nccl            |  Optional NCCL URL or s3 bucket path"
 	    echo "  --cudnn           |  Optional cuDNN URL or s3 bucket path"
+	    echo "  --tensorrt        |  Optional TensorRT URL or s3 bucket path"
 	    echo "  --use-nvidia-ebs  |  Use an NVIDIA ebs (that you've created) which hosts NCCL and cuDNN"
 	    echo ""
 	    echo "  ImageStream Configuration"
@@ -154,6 +155,11 @@ while test $# -gt 0; do
 	    CUDNN=${1}
 	    shift
 	    ;;
+	--tensorrt)
+            shift
+	    TENSORRT=${1}
+	    shift
+	    ;;
 	--s2i-imagestream)
 	    shift
 	    S2I_IMAGESTREAM=${1}
@@ -210,6 +216,12 @@ if [[ -z ${RHEL_VERSION} ]]; then
     RHEL_VERSION=7
 fi
 
+# Check TensorRT (since there is no TensorRT for RHEL 8 yet)
+if [[ ${RHEL_VERSION} == "8" ]] && [[ ! -z ${TENSORRT} ]]; then
+    echo "ERROR. Cannot use TensorRT with RHEL 8 right now as there is no TensorRT package for RHEL 8 available at this time."
+    exit 1
+fi
+
 # Check if backend was supplied
 if [[ -z ${BACKEND} ]]; then
     echo "WARNING. Backend was not supplied. Using FFTW. If you would like to use OpenBLAS or no backend at all, rerun this script using the '-b' or '--backend' argument."
@@ -247,6 +259,8 @@ if [[ ! -z ${AVX} ]]; then
 elif [[ ! -z ${USE_GPU} ]]; then
     if [[ ${BACKEND} == "none" ]]; then
         build_image_template_name="tensorflow-pip-build-image-rhel${RHEL_VERSION}-gpu"
+    elif [[ ${RHEL_VERSION} == "7" ]]; then
+        build_image_template_name="tensorflow-${BACKEND}-build-image-ubi${RHEL_VERSION}-gpu"
     else
         build_image_template_name="tensorflow-${BACKEND}-build-image-rhel${RHEL_VERSION}-gpu"
     fi
@@ -264,11 +278,13 @@ fi
 # Initialize image name (if not specified)
 if [[ -z ${IS_NAME} ]]; then
     if [[ ! -z ${AVX} ]]; then
-        IS_NAME="tensorflow-${BACKEND}-rhel${RHEL_VERSION}-${AVX}"
+        IS_NAME="tensorflow-${BACKEND}-base-rhel${RHEL_VERSION}-${AVX}"
     elif [[ ${BACKEND} == "none" ]]; then
-        IS_NAME="tensorflow-official-rhel${RHEL_VERSION}-${device}"
+        IS_NAME="tensorflow-official-base-rhel${RHEL_VERSION}-${device}"
+    elif [[ ! -z ${USE_GPU} ]] && [[ ${RHEL_VERSION} == "7" ]]; then
+	IS_NAME="tensorflow-${BACKEND}-base-ubi${RHEL_VERSION}-${device}"
     else
-        IS_NAME="tensorflow-${BACKEND}-rhel${RHEL_VERSION}-${device}"
+        IS_NAME="tensorflow-${BACKEND}-base-rhel${RHEL_VERSION}-${device}"
     fi
 fi
 
@@ -364,11 +380,14 @@ if [[ ${use_aws} == "true" ]]; then
     echo "" >> ${makefile}
 fi
 
-# Initialize NCCL and cuDNN setup
+# Initialize NCCL and cuDNN setup. Also initialize TensorRT setup
 if [[ ! -z ${NCCL} ]] && [[ ! -z ${CUDNN} ]]; then
     echo "# NCCL and cuDNN setup" >> ${makefile}
     echo "NCCL=${NCCL}" >> ${makefile}
     echo "CUDNN=${CUDNN}" >> ${makefile}
+    if [[ ! -z ${TENSORRT} ]]; then
+        echo "TENSORRT=${TENSORRT}" >> ${makefile}
+    fi
     echo "" >> ${makefile}
 fi
 
@@ -432,7 +451,11 @@ elif [[ ${device} == "gpu" ]]; then
     elif [[  ${use_aws} == "true" ]]; then
         echo -e "\toc new-app ${s2i_image_template_param} ${source_imagestream_name_param} ${output_imagestream_name_param} ${rhel_version_param} ${num_gpus_param} ${python_executable_param} ${instance_type_param}--param=WHICH_SOURCE='s3' --param=AWS_ACCESS_KEY=\$(AWS_ACCESS_KEY) --param=AWS_SECRET_ACCESS_KEY=\$(AWS_SECRET_ACCESS_KEY) --param=AWS_REGION=\$(AWS_REGION) --param=NCCL_URL=\$(NCCL) --param=CUDNN_URL=\$(CUDNN) --param=AWS_PROFILE=\$(AWS_PROFILE)" >> ${makefile}
     elif [[ ! -z ${NCCL} ]] && [[ ! -z ${CUDNN} ]]; then
-        echo -e "\toc new-app ${s2i_image_template_param} ${source_imagestream_name_param} ${output_imagestream_name_param} ${rhel_version_param} ${num_gpus_param} ${python_executable_param} ${instance_type_param} --param=WHICH_SOURCE='url' --param=NCCL_URL=\$(NCCL) --param=CUDNN_URL=\$(CUDNN)" >> ${makefile}
+	if [[ ! -z ${TENSORRT} ]]; then
+	    echo -e "\toc new-app ${s2i_image_template_param} ${source_imagestream_name_param} ${output_imagestream_name_param} ${rhel_version_param} ${num_gpus_param} ${python_executable_param} ${instance_type_param} --param=WHICH_SOURCE='url' --param=NCCL_URL=\$(NCCL) --param=CUDNN_URL=\$(CUDNN) --param=TENSORRT_URL=\$(TENSORRT)" >> ${makefile}
+	else
+            echo -e "\toc new-app ${s2i_image_template_param} ${source_imagestream_name_param} ${output_imagestream_name_param} ${rhel_version_param} ${num_gpus_param} ${python_executable_param} ${instance_type_param} --param=WHICH_SOURCE='url' --param=NCCL_URL=\$(NCCL) --param=CUDNN_URL=\$(CUDNN)" >> ${makefile}
+        fi
     else
         echo -e "\toc new-app ${s2i_image_template_param} ${source_imagestream_name_param} ${output_imagestream_name_param} ${rhel_version_param} ${num_gpus_param} ${python_executable_param} ${instance_type_param} --param=WHICH_SOURCE='none'" >> ${makefile}
     fi
