Merging '.s2i_fftw' with '.s2i_openblas' into simply '.s2i'. Updating all affected files.

diff --git a/TensorFlow/.s2i/bin/assemble b/TensorFlow/.s2i/bin/assemble
--- a/TensorFlow/.s2i/bin/assemble
+++ b/TensorFlow/.s2i/bin/assemble
@@ -43,9 +43,17 @@ elif [[ ${WHICH_SOURCE} == "ebs" ]] || [[ ${WHICH_SOURCE} == "EBS" ]]; then
 elif [[ ${WHICH_SOURCE} == "none" ]] || [[ ${WHICH_SOURCE} == "NONE" ]]; then
     echo "  Self installed"
 else
-    echo "ERROR. Unrecognized source '${WHICH_SOURCE}'. Please choose from one of the following: {url, s3}"
+    echo "ERROR. Unrecognized source '${WHICH_SOURCE}'. Please choose from one of the following: {url, ebs, s3, none}"
     exit 1
 fi
+
+# Check which backend
+echo "Checking which BLAS backend will be used:"
+if [[ ${BACKEND} != "openblas" ]] && [[ ${BACKEND} != "fftw" ]]; then
+    echo "ERROR. Unrecognized backend '${BACKEND}'. Please choose from one of the following: {fftw, openblas}"
+    exit 1
+fi
+echo "  Using ${BACKEND}"
 
 # Check the current directory
 echo ""
@@ -291,32 +299,64 @@ if [[ ${DEVICE} == "gpu" ]]; then
     
 fi
 
-
 ##########################################
 #         BUILD AND INSTALL FFTW         #
 ##########################################
-# Set install and build dirs
-FFTW_INSTALL_DIR="${TOPDIR}/custom_fftw"
-FFTW_BUILD_DIR="${TOPDIR}/build"
+if [[ ${BACKEND} == "fftw" ]]; then
 
-# Print out info
-echo "FFTW installation params:"
-echo "  Install path: ${FFTW_INSTALL_DIR}"
-echo "  Build path:   ${FFTW_BUILD_DIR}"
-echo "  RHEL version: ${RHEL_VERSION}"
-echo "  CC:           ${CC}"
-echo ""
+    # Set install and build dirs
+    BLAS_INSTALL_DIR="${TOPDIR}/custom_fftw"
+    BLAS_BUILD_DIR="${TOPDIR}/build"
 
-# Change to appropriate directory
-cd ${TOPDIR}/playbooks/FFTW_installation
+    # Print out info
+    echo "FFTW installation params:"
+    echo "  Install path: ${BLAS_INSTALL_DIR}"
+    echo "  Build path:   ${BLAS_BUILD_DIR}"
+    echo "  RHEL version: ${RHEL_VERSION}"
+    echo "  CC:           ${CC}"
+    echo ""
 
-# Build and install FFTW
-ansible-playbook -i hosts play.yaml --extra-vars="{install_dir: '${FFTW_INSTALL_DIR}', build_dir: '${FFTW_BUILD_DIR}', rhel_version: '${RHEL_VERSION}', cc: '${CC}', s2i: 'yes'}"
+    # Change to appropriate directory
+    cd ${TOPDIR}/playbooks/FFTW_installation
 
-# Print out success message
-echo ""
-echo "<< SUCCESS >> FFTW built and installed!"
-echo ""
+    # Build and install FFTW
+    ansible-playbook -i hosts play.yaml --extra-vars="{install_dir: '${BLAS_INSTALL_DIR}', build_dir: '${BLAS_BUILD_DIR}', rhel_version: '${RHEL_VERSION}', cc: '${CC}', s2i: 'yes'}"
+
+    # Print out success message
+    echo ""
+    echo "<< SUCCESS >> FFTW built and installed!"
+    echo ""
+fi
+
+##########################################
+#       BUILD AND INSTALL OPENBLAS       #
+##########################################
+if [[ ${BACKEND} == "openblas" ]]; then
+
+    # Set install and build dirs
+    BLAS_INSTALL_DIR="${TOPDIR}/custom_openblas"
+    BLAS_BUILD_DIR="${TOPDIR}/build"
+    BLAS_WORK_DIR="${TOPDIR}/openblas_tests"
+
+    # Print out info
+    echo "OpenBLAS installation params:"
+    echo "  Install path: ${BLAS_INSTALL_DIR}"
+    echo "  Build path:   ${BLAS_BUILD_DIR}"
+    echo "  RHEL version: ${RHEL_VERSION}"
+    echo "  CC:           ${CC}"
+    echo ""
+
+    # Change to appropriate directory
+    cd ${TOPDIR}/playbooks/OpenBLAS_installation
+
+    # Build and install FFTW
+    ansible-playbook -i hosts play.yaml --extra-vars="{install_dir: '${BLAS_INSTALL_DIR}', build_dir: '${BLAS_BUILD_DIR}', work_dir: '${BLAS_WORK_DIR}'}"
+
+    # Print out success message
+    echo ""
+    echo "<< SUCCESS >> OpenBLAS built and installed!"
+    echo ""
+fi
 
 ##########################################
 #      BUILD AND INSTALL TENSORFLOW      #
@@ -356,14 +396,14 @@ if [[ ${DEVICE} == "cpu" ]]; then
     else
 	PATH_TO_PYTHON_SITE_PKGS="/usr/lib64/python3.6/site-packages"
     fi
-    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '${RHEL_VERSION}', cc: '${CC}', gcc_libs: '${GCC_LIBS}', blas_library_dirs: '${FFTW_INSTALL_DIR}/lib', blas_include_dirs: '${FFTW_INSTALL_DIR}/include', tf_install_dir: '${TENSORFLOW_INSTALL_DIR}', pythonpath: '${PATH_TO_PYTHON_SITE_PKGS}', ansible_python_interpreter: '${PYTHON_EXECUTABLE}', python_executable: '${PYTHON_EXECUTABLE}', use_s2i: 'yes'}"
+    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '${RHEL_VERSION}', cc: '${CC}', gcc_libs: '${GCC_LIBS}', blas_library_dirs: '${BLAS_INSTALL_DIR}/lib', blas_include_dirs: '${BLAS_INSTALL_DIR}/include', tf_install_dir: '${TENSORFLOW_INSTALL_DIR}', pythonpath: '${PATH_TO_PYTHON_SITE_PKGS}', ansible_python_interpreter: '${PYTHON_EXECUTABLE}', python_executable: '${PYTHON_EXECUTABLE}', use_s2i: 'yes'}"
 else
     if [[ ${PYTHON_EXECUTABLE} != "/usr/bin/python3" ]]; then
 	PATH_TO_PYTHON_SITE_PKGS="/usr/local/lib/python3.6/site-packages"
     else
 	PATH_TO_PYTHON_SITE_PKGS="/usr/lib64/python3.6/site-packages"
     fi
-    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '${RHEL_VERSION}', cc: '${CC}', gcc_libs: '${GCC_LIBS}', blas_library_dirs: '${FFTW_INSTALL_DIR}/lib', blas_include_dirs: '${FFTW_INSTALL_DIR}/include', tf_install_dir: '${TENSORFLOW_INSTALL_DIR}', device: 'gpu', nccl_install_path: '${NCCL_INSTALL_PATH}', pythonpath: '${PATH_TO_PYTHON_SITE_PKGS}', ansible_python_interpreter: '${PYTHON_EXECUTABLE}', python_executable: '${PYTHON_EXECUTABLE}', use_s2i: 'yes'}"
+    ansible-playbook -i hosts play.yaml --extra-vars="{rhel_version: '${RHEL_VERSION}', cc: '${CC}', gcc_libs: '${GCC_LIBS}', blas_library_dirs: '${BLAS_INSTALL_DIR}/lib', blas_include_dirs: '${BLAS_INSTALL_DIR}/include', tf_install_dir: '${TENSORFLOW_INSTALL_DIR}', device: 'gpu', nccl_install_path: '${NCCL_INSTALL_PATH}', pythonpath: '${PATH_TO_PYTHON_SITE_PKGS}', ansible_python_interpreter: '${PYTHON_EXECUTABLE}', python_executable: '${PYTHON_EXECUTABLE}', use_s2i: 'yes'}"
 fi
 
 # Print out success message
