Updating 'configure' and instructions in README. Also adding a 'setup' folder for setting up 'aws_env.sh', which is to be consumed by Kubernetes Dockerfiles

diff --git a/TensorFlow/Kubernetes/configure b/TensorFlow/Kubernetes/configure
--- a/TensorFlow/Kubernetes/configure
+++ b/TensorFlow/Kubernetes/configure
@@ -8,45 +8,53 @@ while test $# -gt 0; do
             echo "This script configures the OpenShift TensorFlow benchmarking app"
             echo ""
             echo "[REQUIRED]"
-            echo "  -s, --pull-secret  |  Pull secret name for pulling images from registry.redhat.io or the OpenShift Image Registry namespace. (You must have already created and loaded the secret into OpenShift.)"
-	    echo "  -d, --num-devices  |  Number of devices (CPU or GPU) to use."
-	    echo "  -i, --image        |  The full url to your image, along with the image tag (e.g., quay.io/example/tensorflow:sometag)"
+	    echo "  -v, --rhel-version     |  Version of RHEL to use. (Currently, only RHEL 7 is supported.)"
+            echo "  -s, --pull-secret      |  Pull secret name for pulling images from registry.redhat.io or the OpenShift Image Registry namespace. (You must have already created and loaded the secret into OpenShift.)"
+	    echo "  -d, --num-devices      |  Number of devices (CPU or GPU) to use."
+	    echo "  -i, --image            |  The full url to your image, along with the image tag (e.g., quay.io/example/tensorflow:sometag)"
+            echo "  -b, --backend          |  NumPy backend to use with TensorFlow. Choose from: {fftw, openblas, none}" 
             echo ""
             echo "[OPTIONAL]"
-	    echo "  Automatic Name Generation Configuration"
-	    echo "  -----------------------------"
-	    echo "  For autogenerating names, pass in the following values:"
-            echo "    -b, --backend      |  NumPy backend to use with TensorFlow. Choose from: {fftw, openblas, none}" 
-	    echo "        --use-gpu      |  Specify that you're using the GPU"
+	    echo "  GPU Configuration" 
+	    echo "  ---------------------------"
+	    echo "  -g, --use-gpu          |  Specify that you're using the GPU"
 	    echo ""
 	    echo "  Deployment Configuration"
-	    echo "  ------------------------"
+	    echo "  ---------------------------"
 	    echo "  -n, --deployment-name  |  Custom deployment name (e.g., 'my-tensorflow-fftw-gpu-deployment'). Default name: tensorflow-[BACKEND]-[DEVICE]-deployment"
 	    echo ""
 	    echo "  Instance Type Configuration"
 	    echo "  ---------------------------"
 	    echo "  Specify exact instance:"
-            echo "    -t, --instance-type |  Instance type (e.g., m4.4xlarge, m4.large, etc.). Currently cannot be combined with AVX* instructions (this is a TODO)"
+            echo "    -t, --instance-type  |  Instance type (e.g., m4.4xlarge, m4.large, etc.). Currently cannot be combined with AVX* instructions (this is a TODO)"
 	    echo ""
 	    echo "  Specify instance based on AVX* instructions:"
-            echo "    --use-avx           |  Use AVX instructions"
-	    echo "    --use-avx2          |  Use AVX and AVX2 instructions"
-	    echo "    --use-avx512        |  Use AVX, AVX2, and AVX512 instructions"
+            echo "    --use-avx            |  Use AVX instructions"
+	    echo "    --use-avx2           |  Use AVX and AVX2 instructions"
+	    echo "    --use-avx512         |  Use AVX, AVX2, and AVX512 instructions"
 	    echo ""
 	    echo "  CPU Manager Configuration"
-	    echo "  -------------------------"
-	    echo "  --cpu-mgr     |  Use the CPU manager"
-	    echo "  -m, --memory  |  Amount of memory (resources) to allocate"
+	    echo "  ---------------------------"
+	    echo "  --cpu-mgr              |  Use the CPU manager"
+	    echo "  -m, --memory           |  Amount of memory (resources) to allocate"
 	    exit 1
+	    ;;
+	-v|--rhel-version)
+	    shift
+	    if [[ ${1} != "7" ]]; then
+	        echo "ERROR. RHEL ${1} is not supported at this time. The only supported OS is RHEL 7 at this time."
+		exit 1
+	    fi
+	    RHEL_VERSION=${1}
+	    shift
 	    ;;
 	-b|--backend)
 	    shift
 	    if [[ ${1} != "fftw" ]] && [[ ${1} != "openblas" ]] && [[ ${1} != "none" ]]; then
 	        echo "ERROR. Invalid backend choice. Choose from: {fftw, openblas, none}"
 		exit 1
-	    else
-		BACKEND=${1}
 	    fi
+	    BACKEND=${1}
             shift
 	    ;;
 	-d|--num-devices)
@@ -116,6 +124,12 @@ done
 ###########################################
 #           Check user's inputs           #
 ###########################################
+# Check if user supplied 'RHEL_VERSION'
+if [[ -z ${RHEL_VERSION} ]]; then
+    echo "ERROR. Please supply a RHEL version."
+    exit 1
+fi
+
 # Check if image url was supplied
 if [[ -z ${IMAGE_URL} ]]; then
     echo "ERROR. TensorFlow image url was not provided. Please provide a url to your pre-built TensorFlow image using the '-i' or '--image' flag. Exiting now."
@@ -191,8 +205,36 @@ if [[ -z ${DEPLOYMENT_NAME} ]]; then
     fi
 fi
 
+# Set Dockerfile name
+if [[ ${BACKEND} == "fftw" ]]; then
+    blas_folder="FFTW_backend"
+else
+    blas_folder="OpenBLAS_backend"
+fi
+if [[ ${RHEL_VERSION} == "7" ]]; then
+    os_type="ubi7"
+else
+    os_type="ubi8"
+fi
+if [[ ${device} == "gpu" ]]; then
+    cuda_version="10" #hard coded for now since there are no CUDA 10.1 builds yet
+    dockerfile_path="../Dockerfiles/${blas_folder}/Dockerfile.kubernetes_${os_type}_cuda${cuda_version}"
+else
+    dockerfile_path="../Dockerfiles/${blas_folder}/Dockerfile.kubernetes_${os_type}"
+fi
+
 # Initialize app name
 APP_NAME="tensorflow-${BACKEND}-${device}"
+
+# Find out if we're using podman or docker
+if [[ ! -z `which podman` ]]; then
+    image_builder=`which podman`
+elif [[ ! -z `which docker` ]]; then 
+    image_builder=`which docker`
+else
+    echo "ERROR. Could not find podman or docker for building images"
+    exit 1
+fi
 
 ###########################################
 #    Save configure options to Makefile   #
@@ -203,9 +245,8 @@ makefile="./Makefile"
 # Set YAML file
 deployment_yaml="tensorflow-deployment.yaml"
 
-# Remove existing makefile and YAML
+# Remove existing Makefile
 rm -f ${makefile}
-rm -f ${deployment_yaml}
 
 # Populate Makefile vars
 echo "# Kubernetes names" >> ${makefile}
@@ -213,12 +254,20 @@ echo "DEPLOYMENT_NAME=${DEPLOYMENT_NAME}" >> ${makefile}
 echo "APP_NAME=${APP_NAME}" >> ${makefile}
 echo "" >> ${makefile}
 echo "# Image info" >> ${makefile}
-echo "IMAGE=${IMAGE_URL}" >> ${makefile}
+echo "IMAGE_BUILDER=${image_builder}" >> ${makefile}
+echo "DOCKERFILE=${dockerfile_path}" >> ${makefile}
+echo "IMAGE_NAME=${IMAGE_URL}" >> ${makefile}
 echo "PULL_SECRET=${PULL_SECRET}" >> ${makefile}
 echo "" >> ${makefile}
 echo "# Benchmark info" >> ${makefile}
 echo "NUM_DEVICES=${NUM_DEVICES}" >> ${makefile}
-echo "" >>  ${makefile}
+echo "" >> ${makefile}
+echo "# YAML info" >> ${makefile}
+echo "DEPLOYMENT_YAML=${deployment_yaml}" >> ${makefile}
+echo "" >> ${makefile}
+echo "# Directory to AWS config and credentials"
+echo "AWS_DIR=${AWS_DIR}" >> ${makefile}
+echo "" >> ${makefile}
 
 # Optional: instance type setting
 if [[ ! -z ${INSTANCE_TYPE} ]]; then
@@ -226,19 +275,38 @@ if [[ ! -z ${INSTANCE_TYPE} ]]; then
     echo "" >> ${makefile}
 fi
 
-# Set 
-echo "all: generate_yaml add_deployment" >> ${makefile}
+# Set targets
+echo "all: set_aws_env build_image push_image generate_yaml add_deployment" >> ${makefile}
+echo "" >> ${makefile}
+echo "set_aws_env:" >> ${makefile}
+echo -e "\t"
+
+all: update_yamls add_secrets
+
+update_yamls:
+        sh update_secret_yamls.sh $(HOME_DIR)/.aws/credentials $(HOME_DIR)/.aws/config $(PROFILE)
+
+echo "build_image:" >> ${makefile}
+echo -e "\t\$(IMAGE_BUILDER) -f \$(DOCKERFILE) ../.. --tag \$(IMAGE_NAME)" >> ${makefile}
+echo "" >> ${makefile}
+echo "push_image:" >> ${makefile}
+echo -e "\t\$(IMAGE_BUILDER) push \$(IMAGE_NAME)" >> ${makefile}
 echo "" >> ${makefile}
 echo "generate_yaml:" >> ${makefile}
 if [[ -z ${INSTANCE_TYPE} ]]; then
-    echo -e "\techo -e \"apiVersion: apps/v1\\\nkind: Deployment\\\nmetadata:\\\n  name: \$(DEPLOYMENT_NAME)\\\n  labels:\\\n    app: \$(APP_NAME)\\\nspec:\\\n  replicas: 1\\\n  selector:\\\n    matchLabels:\\\n      app: \$(APP_NAME)\\\n  template:\\\n    metadata:\\\n      labels:\\\n        app: \$(APP_NAME)\\\n    spec:\\\n      containers:\\\n      - name: \$(APP_NAME)\\\n        image: \$(IMAGE)\\\n        ports:\\\n        - containerPort: 80\\\n      imagePullSecrets:\\\n      - name: \$(PULL_SECRET)\\\n      env:\\\n      - name: NUM_DEVICES\\\n        value: \$(NUM_DEVICES)\" >> ${deployment_yaml}" >> ${makefile}
+    echo -e "\techo -e \"apiVersion: apps/v1\\\nkind: Deployment\\\nmetadata:\\\n  name: \$(DEPLOYMENT_NAME)\\\n  labels:\\\n    app: \$(APP_NAME)\\\nspec:\\\n  replicas: 1\\\n  selector:\\\n    matchLabels:\\\n      app: \$(APP_NAME)\\\n  template:\\\n    metadata:\\\n      labels:\\\n        app: \$(APP_NAME)\\\n    spec:\\\n      containers:\\\n      - name: \$(APP_NAME)\\\n        image: \$(IMAGE_NAME)\\\n        ports:\\\n        - containerPort: 80\\\n        env:\\\n        - name: NUM_DEVICES\\\n          value: \\\"\$(NUM_DEVICES)\\\"\\\n      imagePullSecrets:\\\n      - name: \$(PULL_SECRET)\" > \$(DEPLOYMENT_YAML)" >> ${makefile}
 else
-    echo -e "\techo -e \"apiVersion: apps/v1\\\nkind: Deployment\\\nmetadata:\\\n  name: \$(DEPLOYMENT_NAME)\\\n  labels:\\\n    app: \$(APP_NAME)\\\nspec:\\\n  replicas: 1\\\n  selector:\\\n    matchLabels:\\\n      app: \$(APP_NAME)\\\n  template:\\\n    metadata:\\\n      labels:\\\n        app: \$(APP_NAME)\\\n    spec:\\\n      containers:\\\n      - name: \$(APP_NAME)\\\n        image: \$(IMAGE)\\\n        ports:\\\n        - containerPort: 80\\\n      imagePullSecrets:\\\n      - name: \$(PULL_SECRET)\\\n      env:\\\n      - name: NUM_DEVICES\\\n        value: \$(NUM_DEVICES)\\\n      nodeSelector:\\\n        beta.kubernetes.io/instance-type: \$(INSTANCE_TYPE)\" >> ${deployment_yaml}" >> ${makefile}
+    echo -e "\techo -e \"apiVersion: apps/v1\\\nkind: Deployment\\\nmetadata:\\\n  name: \$(DEPLOYMENT_NAME)\\\n  labels:\\\n    app: \$(APP_NAME)\\\nspec:\\\n  replicas: 1\\\n  selector:\\\n    matchLabels:\\\n      app: \$(APP_NAME)\\\n  template:\\\n    metadata:\\\n      labels:\\\n        app: \$(APP_NAME)\\\n    spec:\\\n      containers:\\\n      - name: \$(APP_NAME)\\\n        image: \$(IMAGE_NAME)\\\n        ports:\\\n        - containerPort: 80\\\n        env:\\\n        - name: NUM_DEVICES\\\n          value: \\\"\$(NUM_DEVICES)\\\"\\\n      imagePullSecrets:\\\n      - name: \$(PULL_SECRET)\\\n      nodeSelector:\\\n        beta.kubernetes.io/instance-type: \$(INSTANCE_TYPE)\" > \$(DEPLOYMENT_YAML)" >> ${makefile}
 fi
 
 echo "" >> ${makefile}
 echo "add_deployment:" >> ${makefile}
-echo -e "\tkubectl create -f ${deployment_yaml}" >> ${makefile}
+echo -e "\tkubectl create -f \$(DEPLOYMENT_YAML)" >> ${makefile}
 echo "" >> ${makefile}
-echo "clean:" >> ${makefile}
-echo -e "\tkubectl delete -f ${deployment_yaml}" >> ${makefile}
+echo "clean: clean_deployment clean_image" >> ${makefile}
+echo "" >> ${makefile}
+echo "clean_image:" >> ${makefile}
+echo -e "\t\$(IMAGE_BUILDER) rmi \$(IMAGE_NAME)" >> ${makefile}
+echo "" >> ${makefile}
+echo "clean_deployment:" >> ${makefile}
+echo -e "\tkubectl delete -f \$(DEPLOYMENT_YAML)" >> ${makefile}
